'use client';
import { useEffect, useState } from 'react';
import { api, Case, ToolRun, WS_BASE } from '@/lib/api';

const tone: Record<string, string> = { queued: 'text-slate-400', running: 'text-cyan', completed: 'text-lime', failed: 'text-red-300', rate_limited: 'text-amber' };

export default function CaseMonitor({ caseId }: { caseId: string }) {
  const [item, setItem] = useState<Case | null>(null); const [runs, setRuns] = useState<ToolRun[]>([]); const [message, setMessage] = useState('Connecting to case telemetry…'); const [error, setError] = useState('');
  const refresh = async () => { try { const [c, r] = await Promise.all([api.case(caseId), api.toolRuns(caseId)]); setItem(c); setRuns(r); } catch (e) { setError(e instanceof Error ? e.message : 'Unable to load case.'); } };
  useEffect(() => { refresh(); const interval = setInterval(refresh, 4000); const socket = new WebSocket(`${WS_BASE}/ws/progress/${caseId}`); socket.onmessage = (e) => { try { const d = JSON.parse(e.data); setMessage(`${d.tool}: ${d.status}${d.results_count ? ` · ${d.results_count} results` : ''}`); refresh(); } catch { setMessage(e.data); } }; socket.onerror = () => setMessage('Live stream unavailable; polling case state every 4 seconds.'); return () => { clearInterval(interval); socket.close(); }; }, [caseId]);
  if (error) return <p className="rounded border border-red-400/50 bg-red-500/10 p-4 text-red-200">{error}</p>;
  return <div className="space-y-6">{item && <section className="rounded-xl border border-line bg-panel p-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs text-slate-500">CASE ID · {item.id}</p><h1 className="mt-2 text-2xl text-slate-100">{item.query}</h1><p className="mt-2 text-sm text-slate-400">{item.input_type.toUpperCase()} · Investigation {item.investigation_id}</p></div><span className={`rounded border border-current px-3 py-2 text-xs ${tone[item.status] || 'text-slate-400'}`}>{item.status.toUpperCase()}</span></div><p className="mt-5 border-t border-line pt-4 text-xs text-cyan">LIVE · {message}</p></section>}<section className="rounded-xl border border-line bg-panel p-6"><h2 className="mb-4 text-sm tracking-wider text-slate-200">TOOL RUNS</h2><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{runs.map((run) => <div key={run.id} className="rounded border border-line bg-ink p-4"><div className="flex justify-between gap-3"><span className="text-sm">{run.tool}</span><span className={`text-xs ${tone[run.status] || 'text-slate-400'}`}>{run.status}</span></div><p className="mt-3 text-xs text-slate-400">Results: {run.results_count}</p>{run.error_message && <p className="mt-2 text-xs text-red-200">{run.error_message}</p>}</div>)}</div>{!runs.length && <p className="text-sm text-slate-400">Tool runs will appear when the worker starts.</p>}</section><section className="rounded-xl border border-line bg-panel p-6"><h2 className="mb-4 text-sm tracking-wider text-slate-200">NORMALIZED RESULTS</h2><div className="overflow-x-auto"><table className="min-w-full text-left text-xs"><thead className="border-b border-line text-slate-500"><tr><th className="p-3">TOOL</th><th className="p-3">SITE / TYPE</th><th className="p-3">CONFIDENCE</th><th className="p-3">SOURCE</th><th className="p-3">DATA</th></tr></thead><tbody>{item?.results.map((row) => <tr key={row.id} className="border-b border-line/70 align-top"><td className="p-3 text-cyan">{row.tool}</td><td className="p-3">{row.site || '—'}</td><td className="p-3">{row.confidence}</td><td className="max-w-xs break-all p-3">{row.url ? <a href={row.url} target="_blank" rel="noreferrer">{row.url}</a> : '—'}</td><td className="max-w-sm break-words p-3 text-slate-400">{JSON.stringify(row.extracted_data)}</td></tr>)}</tbody></table></div>{item && !item.results.length && <p className="text-sm text-slate-400">No normalized results have been saved yet.</p>}</section></div>;
}
